REM   Script: 8-3-22
REM   8-3-22


SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM CONTACT_LIST;

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Hockey', 'Minnesota');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(12, 'Baseball', 'California');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Football', 'Texas');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Basketball', 'Indiana');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Volleyball', 'Pennsylvania');

SELECT * FROM IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETES;

SELECT * FROM ATHLETES;

SELECT * FROM ATHLETE;

CREATE TABLE ATHLETE (  
    person_id INT PRIMARY KEY NOT NULL,  
    first_name VARCHAR(25) NOT NULL,  
    last_name VARCHAR(25) NOT NULL  
);

CREATE TABLE ATHLETE (  
    person_id INT PRIMARY KEY NOT NULL,  
    first_name VARCHAR(25) NOT NULL,  
    last_name VARCHAR(25) NOT NULL  
);

ALTER TABLE ATHLETE  
ADD age INT;

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(1, 'Michael' ,'Phelps');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(2, 'Katie', 'ledecky');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(3, 'Usain', 'Bolt');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(4, 'Allyson', 'Felix');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(5, 'Kevin', 'Durant');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(6, 'Diana', 'Taurasi');

UPDATE ATHLETE  
SET age = '32'  
WHERE person_id = '1';

CREATE TABLE CONTACT_LIST (  
    connection_id INT NOT NULL,  
    person_id INT NOT NULL,  
    contact_id INT NOT NULL,  
    favorite VARCHAR(255) NULL  
);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(2,1,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(3,1,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(4,1,5,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(5,1,6,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(6,2,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(7,2,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(8,2,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(9,3,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(10,3,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(11,4,5,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(12,4,6,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(13,5,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(14,5,6,NULL);

UPDATE CONTACT_LIST 
SET favorite = 'y' 
WHERE contact_id = '1';

UPDATE CONTACT_LIST 
SET favorite = 'n' 
WHERE contact_id <> '1';

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(15,1,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(16,2,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(17,1,2,NULL);

SELECT * FROM CONTACT_LIST;

DELETE FROM CONTACT_LIST 
WHERE 
connection_id = '1';

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

SELECT * FROM CONTACT_LIST;

UPDATE CONTACT_LIST 
SET favorite = 'n' 
WHERE connection_id = '1';

SELECT * FROM CONTACT_LIST;

CREATE TABLE IMAGE (   
    image_id INT PRIMARY KEY NOT NULL,   
    image_name VARCHAR(50) NOT NULL,   
    image_location VARCHAR(500) NOT NULL   
);

CREATE TABLE MESSAGE_IMAGE (  
    message_id int NOT NULL,  
    image_id int NOT NULL,  
    PRIMARY KEY (message_id, image_id)  
      
) 
;

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (11, 'Hockey', 'Minnesota');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (12, 'Baseball', 'California');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (13, 'Football', 'Texas');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (14, 'Basketball', 'Indiana');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (15, 'Volleball', 'Pannsylvainia');

select * from IMAGE;

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO MESSAGE_IMAGE  
VALUES (1,1);

INSERT INTO MESSAGE_IMAGE  
VALUES (1,5);

INSERT INTO MESSAGE_IMAGE  
VALUES (2,4);

INSERT INTO MESSAGE_IMAGE  
VALUES (2,3);

INSERT INTO MESSAGE_IMAGE  
VALUES (3,3);

SELECT * FROM MESSAGE_IMAGE;

SELECT S. first_name, S.last_name, R.first_name, R.last_name, M.message_id, M.message, m.send_datetime 
FROM message M, person S, person R 
WHERE M.sender_id= S.person_id 
AND M.reviever_id, =R.person_id 
AND S.first_name = 'Michael' 
AND S.last_name = 'Phelps';

SELECT * FROM ATHLETES;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM IMAGE;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM IMAGE;

SELECT * FROM MESSAGE_IMAGE;

ALTER TABLE ATHLETE ADD Goals INT(3) NULL;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE ADD Goals INT(3) NULL;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Goals INT 
 
SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Goals INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT;ADD  INT; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD PIM INT; 


ADD PPG INT; 


ADD SHG INT; 


ADD SHP INT; 


ADD GWG INT; 


ADD OTG INT; 


ADD S INT; 


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GP INT;

ADD +/- INT; 


ADD PIM INT; 


ADD PPG INT; 


ADD SHG INT; 


ADD SHP INT; 


ADD GWG INT; 


ADD OTG INT; 


ADD S INT; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GP INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD +/- INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD +/- INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD "+/-" INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PIM INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PPG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PPG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD SHG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD SHP INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GWG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD OTG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD S INT;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST, NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID,FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (1, Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID,FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (1, Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
Values (Karill);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME) 
Values (7, Karill);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG OTG, S), 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
(1,"Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
VALUES 
("Karill");

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
VALUES ("Karill");

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ("'Karill', 'Kaprizov', 26, 47, 61, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ('Karill', 'Kaprizov', 26, 47, 61, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ('Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (38, 'Ryan', 'Hartman', 27, 34, 31, 82, 95, 1, 0, 0, 7, 1, 239);

VALUES (22, 'Kevin', 'Fiala', 26, 33, 52, 82, 52, 5, 1, 1, 7, 1, 262); 


SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (22, 'Kevin', 'Fiala', 26, 33, 52, 82, 52, 5, 1, 1, 7, 1, 262);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (34, 'Mats', 'Zuccarello', 34, 24, 55, 70, 24, 7, 0, 0, 2, 0, 159), 
VALUES (14, 'Joel', 'Ericksson Ek', 25, 26, 23, 77, 28, 12, 0, 0, 3, 2, 223);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (14, 'Joel', 'Ericksson Ek', 25, 26, 23, 77, 28, 12, 0, 0, 3, 2, 223);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (34, 'Mats', 'Zuccarello', 34, 24, 55, 70, 24, 7, 0, 0, 2, 0, 159);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (17, 'Marcus', 'Foligno', 30, 23, 19, 74, 5, 0, 0, 3, 1, 98);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (17, 'Marcus', 'Foligno', 30, 23, 19, 74, 112, 5, 0, 0, 3, 1, 98);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (12, 'Matt', 'Boldy', 21, 15, 24, 47, 10, 3, 0, 0, 2, 0, 113);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (29, 'Frederick', 'Gaudreau', 29, 14, 30, 76, 8, 1, 0, 2, 4, 1, 132);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (46, 'Jared', 'Spurgeon', 32, 10, 30, 65, 10, 0, 0, 0, 2, 2, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110), 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110) 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (7, 'Dmitry', 'Kulikov', 31, 7, 17, 80, 39, , 0, 0, 2, 1, 74);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (7, 'Dmitry', 'Kulikov', 31, 7, 17, 80, 39, 0, 0, 0, 2, 1, 74);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Phelps';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Ledecky';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'ledecky';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Bolt';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Felix';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Taurasi';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Durant';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Durant';

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN';


SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN'; 


SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN'; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE 
CHANGE COLUMN PERSON_ID JERSEY_NUMBER;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE;

CHANGE COLUMN PERSON_ID JERSEY_NUMBER


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE 
ORDER BY GOALS DESC;

SELECT * FROM ATHLETE 
ORDER BY AGE DESC;

SELECT * FROM ATHLETE 
ORDER BY PERSON_ID DESC;

SELECT * FROM ATHLETE 
ORDER BY ASSISTS DESC;

SELECT * FROM ATHLETE 
ORDER BY GOALS DESC;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE, 
SELECT * FROM CONTACT_LIST;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE ;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE RENAME COLUMN PERSON_ID TO JERSEY_NUMBER;

SELECT * FROM ATHLETE;

SELECT * FROM contact_list;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST;

RENAME COLUMN CONNECTION_ID TO JERSEY_NUMBER


SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN CONNECTION_ID TO JERSEY_NUMBER;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN PERSON_ID TO CITY;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN CONTACT_ID TO COUNTRY;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN FAVORITE TO SHOOTS;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
DROP COLUMN SHOOTS;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
ADD SHOOTS VARCHAR(50);

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST;

VALUES 


(87, 'NOVOKUZNETSK' , 'RUS' , 'L');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST;

VALUES 


(87, 'NOVOKUZNETSK' , 'RUS' , 'L');

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS');

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'L');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT') 
 
SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT');

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM HOMETOWNS;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM CONTACT_LIST;

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Hockey', 'Minnesota');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(12, 'Baseball', 'California');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Football', 'Texas');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Basketball', 'Indiana');

INSERT INTO IMAGE (image_id, image_name, image_location) 
VALUES(11, 'Volleyball', 'Pennsylvania');

SELECT * FROM IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETES;

SELECT * FROM ATHLETES;

SELECT * FROM ATHLETE;

CREATE TABLE ATHLETE (  
    person_id INT PRIMARY KEY NOT NULL,  
    first_name VARCHAR(25) NOT NULL,  
    last_name VARCHAR(25) NOT NULL  
);

CREATE TABLE ATHLETE (  
    person_id INT PRIMARY KEY NOT NULL,  
    first_name VARCHAR(25) NOT NULL,  
    last_name VARCHAR(25) NOT NULL  
);

ALTER TABLE ATHLETE  
ADD age INT;

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(1, 'Michael' ,'Phelps');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(2, 'Katie', 'ledecky');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(3, 'Usain', 'Bolt');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(4, 'Allyson', 'Felix');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(5, 'Kevin', 'Durant');

INSERT INTO ATHLETE (person_id, first_Name, last_name)  
VALUES(6, 'Diana', 'Taurasi');

UPDATE ATHLETE  
SET age = '32'  
WHERE person_id = '1';

CREATE TABLE CONTACT_LIST (  
    connection_id INT NOT NULL,  
    person_id INT NOT NULL,  
    contact_id INT NOT NULL,  
    favorite VARCHAR(255) NULL  
);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(2,1,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(3,1,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(4,1,5,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(5,1,6,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(6,2,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(7,2,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(8,2,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(9,3,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(10,3,4,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(11,4,5,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(12,4,6,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(13,5,1,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(14,5,6,NULL);

UPDATE CONTACT_LIST 
SET favorite = 'y' 
WHERE contact_id = '1';

UPDATE CONTACT_LIST 
SET favorite = 'n' 
WHERE contact_id <> '1';

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(15,1,3,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(16,2,2,NULL);

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(17,1,2,NULL);

SELECT * FROM CONTACT_LIST;

DELETE FROM CONTACT_LIST 
WHERE 
connection_id = '1';

INSERT INTO CONTACT_LIST (connection_id, person_id, contact_id, favorite)  
VALUES(1,1,2,NULL);

SELECT * FROM CONTACT_LIST;

UPDATE CONTACT_LIST 
SET favorite = 'n' 
WHERE connection_id = '1';

SELECT * FROM CONTACT_LIST;

CREATE TABLE IMAGE (   
    image_id INT PRIMARY KEY NOT NULL,   
    image_name VARCHAR(50) NOT NULL,   
    image_location VARCHAR(500) NOT NULL   
);

CREATE TABLE MESSAGE_IMAGE (  
    message_id int NOT NULL,  
    image_id int NOT NULL,  
    PRIMARY KEY (message_id, image_id)  
      
) 
;

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (11, 'Hockey', 'Minnesota');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (12, 'Baseball', 'California');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (13, 'Football', 'Texas');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (14, 'Basketball', 'Indiana');

INSERT INTO IMAGE(image_id, image_name, image_location) 
VALUES (15, 'Volleball', 'Pannsylvainia');

select * from IMAGE;

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO messgae_image  
VALUES (1,1);

INSERT INTO MESSAGE_IMAGE  
VALUES (1,1);

INSERT INTO MESSAGE_IMAGE  
VALUES (1,5);

INSERT INTO MESSAGE_IMAGE  
VALUES (2,4);

INSERT INTO MESSAGE_IMAGE  
VALUES (2,3);

INSERT INTO MESSAGE_IMAGE  
VALUES (3,3);

SELECT * FROM MESSAGE_IMAGE;

SELECT S. first_name, S.last_name, R.first_name, R.last_name, M.message_id, M.message, m.send_datetime 
FROM message M, person S, person R 
WHERE M.sender_id= S.person_id 
AND M.reviever_id, =R.person_id 
AND S.first_name = 'Michael' 
AND S.last_name = 'Phelps';

SELECT * FROM ATHLETES;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM IMAGE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM IMAGE;

SELECT * FROM MESSAGE_IMAGE;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

SELECT * FROM IMAGE;

SELECT * FROM MESSAGE_IMAGE;

ALTER TABLE ATHLETE ADD Goals INT(3) NULL;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE ADD Goals INT(3) NULL;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Goals INT 
 
SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Goals INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD  INT; 


ADD  INT; 


ADD  INT; 


ADD  INT;ADD  INT; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD Assists INT;

ADD GP INT; 


ADD +/- INT; 


ADD PIM INT; 


ADD PPG INT; 


ADD SHG INT; 


ADD SHP INT; 


ADD GWG INT; 


ADD OTG INT; 


ADD S INT; 


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GP INT;

ADD +/- INT; 


ADD PIM INT; 


ADD PPG INT; 


ADD SHG INT; 


ADD SHP INT; 


ADD GWG INT; 


ADD OTG INT; 


ADD S INT; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GP INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD +/- INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD +/- INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD "+/-" INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PIM INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PPG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD PPG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD SHG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD SHP INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD GWG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD OTG INT;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE   
ADD S INT;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST, NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID,FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, GWG, OTG, S) 
VALUES (1, Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID,FIRST_NAME, LAST_NAME, AGE, GOALS, ASSSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (1, Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (Kirill, Kaprisov, 25, 47, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
Values (Karill);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME) 
Values (7, Karill);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG OTG, S), 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
(1,"Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 31, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES 
("Karill","Kaprizov", 25, 57, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
VALUES 
("Karill");

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME) 
VALUES ("Karill");

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ("'Karill', 'Kaprizov', 26, 47, 61, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ('Karill', 'Kaprizov', 26, 47, 61, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES ('Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289);

VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


VALUES (87, 'Karill', 'Kaprizov', 26, 47, 61, 81, 34, 14, 0, 0, 5, 2, 289); 


SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (38, 'Ryan', 'Hartman', 27, 34, 31, 82, 95, 1, 0, 0, 7, 1, 239);

VALUES (22, 'Kevin', 'Fiala', 26, 33, 52, 82, 52, 5, 1, 1, 7, 1, 262); 


SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (22, 'Kevin', 'Fiala', 26, 33, 52, 82, 52, 5, 1, 1, 7, 1, 262);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (34, 'Mats', 'Zuccarello', 34, 24, 55, 70, 24, 7, 0, 0, 2, 0, 159), 
VALUES (14, 'Joel', 'Ericksson Ek', 25, 26, 23, 77, 28, 12, 0, 0, 3, 2, 223);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (14, 'Joel', 'Ericksson Ek', 25, 26, 23, 77, 28, 12, 0, 0, 3, 2, 223);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (34, 'Mats', 'Zuccarello', 34, 24, 55, 70, 24, 7, 0, 0, 2, 0, 159);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (17, 'Marcus', 'Foligno', 30, 23, 19, 74, 5, 0, 0, 3, 1, 98);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (17, 'Marcus', 'Foligno', 30, 23, 19, 74, 112, 5, 0, 0, 3, 1, 98);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (12, 'Matt', 'Boldy', 21, 15, 24, 47, 10, 3, 0, 0, 2, 0, 113);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (29, 'Frederick', 'Gaudreau', 29, 14, 30, 76, 8, 1, 0, 2, 4, 1, 132);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (46, 'Jared', 'Spurgeon', 32, 10, 30, 65, 10, 0, 0, 0, 2, 2, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110), 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110) 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (18, 'Jordan', 'Greenway', 25, 10, 17, 62, 69, 1, 0, 0, 3, 0, 110);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (24, 'Matt', 'Dumba', 28, 7, 20, 57, 47, 1, 0, 0, 1, 0, 116);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (7, 'Dmitry', 'Kulikov', 31, 7, 17, 80, 39, , 0, 0, 2, 1, 74);

SELECT * FROM ATHLETE;

INSERT INTO ATHLETE (PERSON_ID, FIRST_NAME, LAST_NAME, AGE, GOALS, ASSISTS, GP, PIM, PPG, SHG, SHP, GWG, OTG, S) 
VALUES (7, 'Dmitry', 'Kulikov', 31, 7, 17, 80, 39, 0, 0, 0, 2, 1, 74);

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Phelps';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Ledecky';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'ledecky';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Bolt';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Felix';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Taurasi';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Durant';

SELECT * FROM ATHLETE;

DELETE FROM ATHLETE WHERE LAST_NAME = 'Durant';

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN';


SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN'; 


SELECT * FROM ATHLETE;

sp_RENAME 'Table_ATHLETE.PERSON_ID', 'NUMBER' , 'COLUMN'; 


SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE 
CHANGE COLUMN PERSON_ID JERSEY_NUMBER;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE;

CHANGE COLUMN PERSON_ID JERSEY_NUMBER


SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE 
ORDER BY GOALS DESC;

SELECT * FROM ATHLETE 
ORDER BY AGE DESC;

SELECT * FROM ATHLETE 
ORDER BY PERSON_ID DESC;

SELECT * FROM ATHLETE 
ORDER BY ASSISTS DESC;

SELECT * FROM ATHLETE 
ORDER BY GOALS DESC;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE, 
SELECT * FROM CONTACT_LIST;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE ;

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE RENAME COLUMN PERSON_ID TO JERSEY_NUMBER;

SELECT * FROM ATHLETE;

SELECT * FROM contact_list;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST;

RENAME COLUMN CONNECTION_ID TO JERSEY_NUMBER


SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN CONNECTION_ID TO JERSEY_NUMBER;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN PERSON_ID TO CITY;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN CONTACT_ID TO COUNTRY;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME COLUMN FAVORITE TO SHOOTS;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
DROP COLUMN SHOOTS;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
ADD SHOOTS VARCHAR(50);

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST;

VALUES 


(87, 'NOVOKUZNETSK' , 'RUS' , 'L');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST;

VALUES 


(87, 'NOVOKUZNETSK' , 'RUS' , 'L');

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS');

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'L');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT');

SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT') 
 
SELECT * FROM CONTACT_LIST;

INSERT INTO CONTACT_LIST (JERSEY_NUMBER, CITY, COUNTRY, SHOOTS)   
VALUES(87, 'NOVOKUZNETSK' ,'RUS', 'LEFT');

SELECT * FROM CONTACT_LIST;

SELECT * FROM ATHLETE;

SELECT * FROM HOMETOWN;

SELECT * FROM HOMETOWNS;

SELECT * FROM ATHLETE;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
DROP COLUMN SHOOTS;

ALTER TABLE CONTACT_LIST 
DROP COLUMN SHOOTS;

SELECT * FROM CONTACT_LIST;

ALTER TABLE CONTACT_LIST 
RENAME TO HOMETOWNS;

SELECT * FROM CONTACT_LIST;

SELECT * FROM HOMETOWNS;

SELECT * FROM HOMETOWNS;

SELECT * FROM ATHLETES;

SELECT * FROM HOMETOWNS;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE 
RENAME TO WildPlayers;

SELECT * FROM ATHLETE;

ALTER TABLE ATHLETE 
RENAME TO WildPlayers;

SELECT * FROM WildPlayers;

ALTER TABLE ATHLETE 
RENAME TO WildPlayers;

SELECT * FROM WildPlayers;

SELECT * FROM WildPlayers;

SELECT * FROM ATHLETE;

SELECT * FROM WildPlayers;

SELECT * FROM HOMETOWNS;

DELETE FROM HOMETOWNS WHERE CITY ='1';

SELECT * FROM HOMETOWNS;

DELETE FROM HOMETOWNS WHERE CITY ='2';

SELECT * FROM HOMETOWNS;

DELETE FROM HOMETOWNS WHERE CITY ='3';

SELECT * FROM HOMETOWNS;

DELETE FROM HOMETOWNS WHERE CITY ='4';

SELECT * FROM HOMETOWNS;

DELETE FROM HOMETOWNS WHERE CITY ='5';

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES  
(87, 'NOVOKUZNETSK', 'RUS'), 
(38, 'HILTON HEAD ISLAND, SC', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES (87, 'NOVOKUZNETSK', 'RUS'), 
(38, 'HILTON HEAD ISLAND, SC', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES (87, 'NOVOKUZNETSK', 'RUS');

SELECT * FROM HOMETOWNS;

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES (87, 'NOVOKUZNETSK', 'RUS');

SELECT * FROM HOMETOWNS;

DROP TABLE HOMTOWNS;

SELECT * FROM HOMETOWNS;

SELECT * FROM HOMETOWNS;

SELECT * FROM HOMETOWNS;

DROP TABLE HOMETOWNS;

CREATE TABLE HOMETOWNS(    
    JERSEY_NUMBER INT PRIMARY KEY NOT NULL,    
    CITY VARCHAR(25) NOT NULL,    
    COUNTRY VARCHAR(25) NOT NULL    
) 
 
SELECT * FROM HOMETOWNS;

CREATE TABLE HOMETOWNS(    
    JERSEY_NUMBER INT PRIMARY KEY NOT NULL,    
    CITY VARCHAR(25) NOT NULL,    
    COUNTRY VARCHAR(25) NOT NULL);

SELECT * FROM HOMETOWNS;

INSET INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 


VALUES( 87, 'NOVOKUZNETSK' ,'RUS'); 


SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES( 87, 'NOVOKUZNETSK' ,'RUS');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES( 38, 'HILTON HEAD ISLAND, SC' ,'USA'), 
VALUES( 22, 'ST. GALLEN', 'CHE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES( 38, 'HILTON HEAD ISLAND, SC' ,'USA'), 
( 22, 'ST. GALLEN', 'CHE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 38, 'HILTON HEAD ISLAND, SC' ,'USA'), 
( 22, 'ST. GALLEN', 'CHE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 38, 'HILTON HEAD ISLAND, SC' ,'USA');

( 22, 'ST. GALLEN', 'CHE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 22, 'ST. GALLEN', 'CHE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 14, 'KARLSTAD', 'SWE');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 36, 'OSLO', 'NOR');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 17, 'MILFORD', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 12, 'MILFORD', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 89, 'BROMONT, QC', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 46, 'EDMONTON, AB', 'CAN');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 24, 'REGINA, SK', 'CAN');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 18, 'CANTON, NY', 'USA');

SELECT * FROM HOMETOWNS;

INSERT INTO HOMETOWNS (JERSEY_NUMBER, CITY, COUNTRY) 
VALUES 
( 7, 'LIPETSK', 'RUS');

SELECT * FROM HOMETOWNS;

UPDATE HOMETOWNS 
SET CITY = 'BUFFALO' 
WHERE JERSEY_NUMBER = 17;

SELECT * FROM HOMETOWNS;

UPDATE HOMETOWNS 
SET COUNTRY = 'CAN' 
WHERE JERSEY_NUMBER = 89;

SELECT * FROM HOMETOWNS;

SELECT * FROM WildPlayers 
INNER JOIN HOMETOWNS 
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS 
INNER JOIN HOMETOWNS 
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS 
FROM wildPlayers 
INNER JOIN HOMETOWNS 
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS 
FROM wildPlayers 
INNER JOIN HOMETOWNS 
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS 
FROM WildPlayers 
INNER JOIN HOMETOWNS 
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT SUM(GOALS) AS TOTALGOALS FROM WildPlayers;

SELECT SUM(GOALS) AS TOTALGOALS FROM WildPlayers;

SELECT COUNTRY, SUM(GOALS) FROM WildPlayers GROUP BY COUNTRY;

SELECT COUNTRY, SUM(GOALS) FROM WildPlayers GROUP BY COUNTRY;

SELECT name, SUM(GOALS) FROM WildPlayers GROUP BY name;

SELECT COUNTRY, SUM(GOALS) FROM WildPlayers GROUP BY COUNTRY;

SELECT *  
FROM WildPlayers 
 
SELECT  
COUNTRY,  
SUM(GOALS) AS TOTAL_GOALS 
FROM WildPlayers 
WHERE CONTURY like 'USA';

SELECT *  
FROM WildPlayers 
 
SELECT  
COUNTRY,  
SUM(GOALS) AS TOTAL_GOALS 
FROM WildPlayers 
WHERE CONTURY like 'USA' 
 
 
;

SELECT *  
FROM WildPlayers;

SELECT SUM(GOALS) AS TOTALGOALS FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
WHERE COUTRY(USA) 
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY.USA, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers  
WHERE COUNTRY ='USA';

SELECT * FROM HOMETOWNS  
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER 
 
SELECT * FROM HOMETOWNS  
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM HOMETOWNS  
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers  
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers.JERSEY_NUMBER  
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers 
WHERE COUNTRY ='USA';

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
WHERE COUNTRY = 'USA' 
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

INSERT INTO WildPlayers(COUNTRY) 
VLAUES('CANADA', 'USA');

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

INSERT INTO WildPlayers(COUNTRY) 
VLAUES('CANADA', 'USA');

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

INSERT INTO WildPlayers(COUNTRY) 
VALUES('CANADA', 'USA');

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

INSERT INTO WildPlayers(COUNTRY) 
VALUES('CANADA');

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

ALTER TABLE WildPlayers 
ADD COUTRY;

INSERT INTO WildPlayers(COUNTRY) 
VALUES('CANADA');

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

ALTER TABLE WildPlayers 
ADD COUTRY;

SELECT * FROM WildPlayers;

ALTER TABLE WildPlayers 
ADD COUTRY;

SELECT * FROM WildPlayers;

ALTER TABLE WildPlayers 
ADD COUTRY VARCHAR(255);

SELECT * FROM WildPlayers;

ALTER TABLE WildPlayers 
ADD COUTRY VARCHAR(255);

UPDATE WildPlayers 
SET COUNTRY = 'CAN'  
WHERE JERSEY_NUMBER = 29, 46, 24;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUNTRY = 'CAN'  
WHERE JERSEY_NUMBER = 29, 46, 24;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUNTRY = 'CAN'  
WHERE JERSEY_NUMBER = 29;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'CAN'  
WHERE JERSEY_NUMBER = 29,24,46;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'CAN'  
WHERE JERSEY_NUMBER = 29;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'CAN'  
WHERE JERSEY_NUMBER = 24;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'CAN'  
WHERE JERSEY_NUMBER = 46;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'RUS'  
WHERE JERSEY_NUMBER = 87;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'RUS'  
WHERE JERSEY_NUMBER = 7;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'USA'  
WHERE JERSEY_NUMBER = 38;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'USA'  
WHERE JERSEY_NUMBER = 17;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'USA'  
WHERE JERSEY_NUMBER = 12;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'USA'  
WHERE JERSEY_NUMBER = 18;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'SWE'  
WHERE JERSEY_NUMBER = 14;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'CHE'  
WHERE JERSEY_NUMBER = 22;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET COUTRY = 'NOR'  
WHERE JERSEY_NUMBER = 34;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET JRESEY_NUMBER = 36  
WHERE JERSEY_NUMBER = 34;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET JERSEY_NUMBER = 36  
WHERE JERSEY_NUMBER = 34;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET JERSEY_NUMBER = 29  
WHERE JERSEY_NUMBER = 89;

SELECT * FROM WildPlayers;

UPDATE WildPlayers 
SET JERSEY_NUMBER = 89  
WHERE JERSEY_NUMBER = 29;

SELECT * FROM WildPlayers;

SELECT * FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT * FROM WildPlayers;

ALTER TABLE WildPlayers 
CHANGE COLUMN COUTRY TO COUNTRY;

SELECT * FROM WildPlayers;

ALTER TABLE WildPlayers 
RENAME COLUMN COUTRY TO COUNTRY;

SELECT * FROM WildPlayers;

SELECT AVE(GOALS) 
FROM WildPlayers;

SELECT AVG(GOALS) 
FROM WildPlayers;

SELECT FROM WILDPLAYERS;

SELECT * FROM WILDPLAYERS;

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA' 
 
SELECT SUM(GOALS) AS TOTALUSAGOALS;

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA';

SELECT SUM(GOALS) AS TOTALUSAGOALS;

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA';

SELECT SUM(GOALS) AS TOTALUSAGOALS FROM WILDPLAYERS;

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='USA';

SELECT SUM(GOALS) AS TOTALUSAGOALS FROM WILDPLAYERS WHERE COUNTRY = 'USA';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='CAN';

SELECT SUM(GOALS) AS TOTALUSAGOALS FROM WILDPLAYERS WHERE COUNTRY = 'CAN';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='RUS';

SELECT SUM(GOALS) AS TOTALUSAGOALS FROM WILDPLAYERS WHERE COUNTRY = 'RUS';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='RUS';

SELECT SUM(GOALS) AS TOTALRUSGOALS FROM WILDPLAYERS WHERE COUNTRY = 'RUS';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='CAN';

SELECT SUM(GOALS) AS TOTALCANGOALS FROM WILDPLAYERS WHERE COUNTRY = 'CAN';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='CAN';

SELECT SUM(GOALS) AS TOTALCANGOALS FROM WILDPLAYERS WHERE COUNTRY = 'CAN';

SELECT * FROM WILDPLAYERS 
 
 
SELECT SUM(GOALS) AS TOTALCANGOALS FROM WILDPLAYERS WHERE COUNTRY = 'CAN';

SELECT * FROM WILDPLAYERS;

SELECT SUM(GOALS) AS TOTALCANGOALS FROM WILDPLAYERS WHERE COUNTRY = 'CAN';

SELECT * FROM WILDPLAYERS 
WHERE COUNTRY ='CAN';

SELECT SUM(GOALS, ASSISTS) AS POINTS FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT * FROM WILDPLAYERS;

SELECT SUM(GOALS, ASSISTS) AS POINTS FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT * FROM WILDPLAYERS;

SELECT SUM(GOALS), SUM(ASSISTS) AS POINTS FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT * FROM WILDPLAYERS;

SELECT SUM(GOALS), SUM(ASSISTS)   
FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT * FROM WILDPLAYERS;

SELECT GOALS, ASSISTS  
FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT GOALS, ASSISTS  
FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT GOALS, SUM(ASSISTS)  
FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT SUM(GOALS), SUM(ASSISTS)  
FROM WILDPLAYERS WHERE JERSEY_NUMBER = '87';

SELECT GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT * FROM WILDPLAYERS;

SELECT WildPlayers.JERSEY_NUMBER, CITY, COUNTRY, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT WildPlayers.JERSEY_NUMBER, FIRST_NAME, LAST_NAME, GOALS, ASSISTS  
FROM WildPlayers  
INNER JOIN HOMETOWNS  
ON WildPlayers.JERSEY_NUMBER = HOMETOWNS.JERSEY_NUMBER;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT * FROM WILDPLAYERS;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

SELECT JERSEY_NUMBER, FIRST_NAME, LAST_NAME,GOALS, ASSISTS,(GOALS+ASSISTS) AS POINTS 
FROM WildPlayers;

